Add Two Continuous Variables Pairwise Testing (Correlation Estimate and P Value)
FredHutch/VISCfunctions pull request #70
Opened 2020-10-10 00:52 UTC by wfulp

Takes a continuous variable and a grouping variable to calculate the pairwise Spearman, Pearson, or Kendall correlation estimate and p-value between two variables.

Here is an example of how to you the function:
```
## Antigen Correlation
exampleData_BAMA %>%
  filter(visitno != 0) %>%
  group_by(group, visitno) %>%
   summarize(
     pairwise_test_cor(x = magnitude, group = antigen, id = pubID,
     method = 'spearman', n_distinct_value = 3, digits = 1, verbose = TRUE),
     .groups = 'drop'
             )
```

closes #20

2020-10-14 00:55 UTC, seajane requested changes
Works well overall.  I left some suggestions as I tested each variable. Did you update tests for this function too?

2020-10-14 00:55 UTC, seajane commented on R/pairwise_comparisons.R
> +#' @param group categorical vector which contains the group levels to compare
`pairwise_test_bin` says, "a vector of group values." `pairwise_test_cont` says, "categorical vector of group values.". I suggest choosing one for all, something, like "a categorical vector of group values." for all of the `pairwise...` functions. If you want to add an additional sentence to describe that this is used to provide each pairwise comparison add a new sentence. "Each member is compared to every other group in this vector to form the estimates."

2020-10-14 00:55 UTC, seajane commented on R/pairwise_comparisons.R
> +#' @param id vector which contains the id information
this is inline with the other `pairwise...` functions, but it should probably identify that either categorical or numerical data maybe used.  I could use non-unique values (e.g. `id = rep("a",10)` or `id = rep(5,10)` that produced different results than a vector of unique values. I am not sure if this is intended behavior, or not. If it is intended, then some sort of warning should occur.

2020-10-14 00:55 UTC, seajane commented on R/pairwise_comparisons.R
> +#'   can be abbreviated to "p", "k", or "s".
This should also be updated in `cor_test` too.
```suggestion
#'   can be abbreviated by any truncation of "pearson", "kendall", or "spearman" up to the first initial (e.g. "pear", "k", and "sp" are acceptable abbreviations). 
```

2020-10-14 00:55 UTC, seajane commented on R/pairwise_comparisons.R
> +#' have to be compared.
`num_needed_for_test` in `pairwise_test_cont`, says, "required sample size (per group) to perform test. Note at least 2 distinct values per group are always needed for testing.". `num_needed_for_test` in `pairwise_test_bin` says, "required sample size (per group) to perform test.". The names of the parameters and the descriptions should be standardized. The default value of '3' should be called out here. Note for this function, the "at least two" standard does not hold, but throws a warning for each group of less than two and produces <NA> for CorrEst and NA for CorrTest in the final table.

2020-10-14 00:55 UTC, seajane commented on R/pairwise_comparisons.R
> +#' @param digits digits to round for correlation estimate
```suggestion
#' @param digits numeric value between 0 and 14 indicating the number of digits to round the correlation estimate. The default is set to 3.
```

2020-10-14 00:55 UTC, seajane commented on R/pairwise_comparisons.R
> +#' `TRUE`, output is a character vector.
I get trailing zeros in both `CorrEst` and `CorrTest` whether or not this is TRUE or FALSE. It does change between numeric and character, however.

2020-10-14 00:55 UTC, seajane commented on R/pairwise_comparisons.R
> +#'   should be displayed.
Doesn't work to shut down warnings when group is `n_distinct_value = 1`.

2020-10-14 00:55 UTC, seajane commented on R/pairwise_comparisons.R
> +#' @return Returns a data frame with all possible pairwise correlations.
```suggestion
#' @return Returns a data frame with all pairwise correlations with group sizes greater than or equal to the minimum number of values in group, as set by `n_distinct_value`
```

2020-10-14 00:55 UTC, seajane commented on R/pairwise_comparisons.R
> +#' @return Returns a data frame of all possible pairwise correlations
delete this line.
```suggestion
#' 
```

2020-10-14 00:55 UTC, seajane commented on R/pairwise_comparisons.R
> +#' @param verbose a logical variable indicating if warnings and messages
```suggestion
#' @param verbose logical variable indicating whether warnings and messages
```

2020-10-14 00:55 UTC, seajane commented on R/pairwise_comparisons.R
> +#' @param nresample a positive integer, the number of Monte Carlo replicates
```suggestion
#' @param nresample positive integer indicating the number of Monte Carlo estimates 
```

2020-10-14 00:55 UTC, seajane commented on R/pairwise_comparisons.R
> +#'   used for the computation of the approximative reference distribution.
```suggestion
#'   to use for the computation of the approximate reference distribution.
```

2020-10-14 00:55 UTC, seajane commented on R/pairwise_comparisons.R
> +#'   Defaults to 10000. only used if `method = "spearman"` and there are
```suggestion
#'   Default is set to 10,000. Only used when `method = "spearman"` and there are
```

2020-10-14 00:55 UTC, seajane commented on R/pairwise_comparisons.R
> +#' @param seed seed (only used if `method = "spearman"` and there are
```suggestion
#' @param seed numeric value used to set the seed. Only used if method = "spearman" and there are
```

2020-10-14 00:55 UTC, seajane commented on R/pairwise_comparisons.R
> +#' @param exact should exact method be used. Ignored if
```suggestion
#' @param exact logical value indicating whether the "exact" method should be used. Ignored if
```

2020-10-14 00:55 UTC, seajane commented on R/pairwise_comparisons.R
> +#' * `NPairs` - number of completed pairs
completed?  Word choice is awkward.

2020-10-14 00:55 UTC, seajane commented on R/pairwise_comparisons.R
> +#' * `CorrTest` - correlation p value
```suggestion
#' * `CorrTest` - correlation test p value
```

2020-10-14 00:55 UTC, seajane commented on R/pairwise_comparisons.R
> +#' ## Antigen Correlation
Library in `dplyr` or filter won't work.
```suggestion
#' ## Antigen Correlation
#' library(dplyr)
```

2021-01-11 19:42 UTC, wfulp commented on R/pairwise_comparisons.R
> +#' @param group categorical vector which contains the group levels to compare
changed `pairwise_test_bin` to "categorical vector of group values."

2021-01-11 22:03 UTC, wfulp commented on R/pairwise_comparisons.R
> +#' @param id vector which contains the id information
added length consistency check for id, group, and x

2021-01-11 22:07 UTC, wfulp commented on R/pairwise_comparisons.R
> +#'   can be abbreviated to "p", "k", or "s".
dropped truncate stuff altogether

2021-01-11 22:17 UTC, wfulp commented on R/pairwise_comparisons.R
> +#' have to be compared.
added default amount

2021-01-11 22:39 UTC, wfulp commented on R/pairwise_comparisons.R
> +#' `TRUE`, output is a character vector.
it looks like in newer versions of R and `kable` it will shows numeric with trailing zeros, so this param might not be useful with these newer versions.

2021-01-11 22:47 UTC, wfulp commented on R/pairwise_comparisons.R
> +#'   should be displayed.
Added >1 restriction

2021-01-11 23:02 UTC, wfulp commented on R/pairwise_comparisons.R
> +#'   used for the computation of the approximative reference distribution.
copied language from `coin::NullDistribution`

2021-01-11 23:14 UTC, wfulp commented on R/pairwise_comparisons.R
> +#' ## Antigen Correlation
it's loaded a few lines above

2021-01-11 23:22 UTC, wfulp commented
@seajane Thanks for the detailed comments. I've addressed them

2021-01-13 20:38 UTC, seajane approved these changes
Just a few minor text edits for the vignette.

2021-01-13 20:38 UTC, seajane commented on man/pairwise_test_cor.Rd
> +\item{seed}{seed numeric value used to set the seed. Only used if
drop the word "seed" at the start of this description

2021-01-13 20:38 UTC, seajane commented on man/pairwise_test_cor.Rd
> +\item{method}{a character string indicating which correlation coefficient
drop the "a" at the start of this description so that it aligns with the format of all other descriptions.

2021-01-13 20:38 UTC, seajane commented on man/pairwise_test_cor.Rd
> +have to be compared. The value must be >1, with a default of 3.}
change to "number of distinct values in x each group must contain to be compared..."

2021-01-13 23:05 UTC, merged