Hotfix/cor pair name fix
FredHutch/VISCfunctions pull request #80
Opened 2021-05-26 02:58 UTC by wfulp

Changing `pairwise_test_cor()` to `cor_test_pairs()`, and NDistinct to Ties
Resolves #79. 

Also added some ReadMe updates I left out of the 1.2.0 release

2021-06-01 22:22 UTC, monicagerber requested changes
Thanks Jimmy for making this update! I'm still not sure we want to use the word "pairs" in the function name, so I'm interested in what @mayerbry thinks.

2021-06-01 22:22 UTC, monicagerber commented on NEWS.md
> +* Changing name of `create_step_curve()` to `cor_test_pairs()` and outputting ties instead of number of distinct
```suggestion
* `pairwise_test_cor()` is now named `cor_test_pairs()`. The function `cor_test_pairs()` now returns a data.frame with [ ] instead of [ ].
```
I don't understand what "outputting ties instead of number of distinct" means. Could you clarify this?

2021-06-01 22:22 UTC, monicagerber commented on R/pairwise_comparisons.R
> +#' Correlation Testing for Multiple Groups/Measures
```suggestion
#' Correlation Testing for Multiple Endpoints/Terms
```

2021-06-01 22:22 UTC, monicagerber commented on R/pairwise_comparisons.R
> +#' Takes a continuous variable and a categorical variable, and calculate the
```suggestion
#' Takes a continuous variable and a categorical variable, and calculates the
```

2021-06-01 22:22 UTC, monicagerber commented on R/pairwise_comparisons.R
> +#' pairwise Spearman, Pearson, or Kendall correlation estimate and p-value
```suggestion
#' Spearman, Pearson, or Kendall correlation estimate and p-value
```

2021-06-01 22:22 UTC, monicagerber commented on R/pairwise_comparisons.R
> +#' Correlation Testing for Multiple Groups/Measures
The corrr package uses "term" which we may want to consider. I would go with "Endpoints/Outcomes" or "Endpoints/Terms," but avoid using "Group."

2021-06-01 22:22 UTC, monicagerber commented on NAMESPACE
> +export(cor_test_pairs)
Suggestions:
cor_test_endpoints
cor_test_terms
cor_test_multi
cor_test_all

You could throw out some options and ask VISC group to give input.

2021-06-01 22:22 UTC, monicagerber commented on README.Rmd
> +* `cor_test()` for a Spearman, Pearson, or Kendall correlation test.
Thanks for updating the README!

2021-06-01 22:32 UTC, mayerbry commented
I actually stole "pairs" from `GGally::ggpairs()` since they both generate all bivariate comparisons from a list of inputs. Would it be helpful to contextualize it that way? Regardless, I agree that we can put it to vote in the visc-functions slack channel (I also like cor_test_endpoints).

2021-06-01 23:23 UTC, monicagerber commented on R/pairwise_comparisons.R
> +#' @param group categorical vector which contains the levels to compare
consider naming this "term", "pair", or "endpoint.

2021-06-01 23:25 UTC, monicagerber commented
Ah, I see! Yes, I think it would be helpful to contextualize it that way.

2021-06-03 21:31 UTC, monicagerber approved these changes
Looks great! 🙌🌈🌟

2021-06-03 23:19 UTC, merged